#!/bin/bash

yum update
yum install -y epel-release
yum install -y git curl wget figlet 


chmod 755 os && cp os /usr/bin/
git clone https://github.com/smkn1kejobong/openstack
cd openstack && chmod 755 setup.sh && ./setup.sh
